# sudo required for docker
sudo: true
dist: xenial

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

# Only clone the most recent commit.
git:
  depth: 1

# install qemu-user before running docker build
before_install:
  - env
