# sudo required for docker
sudo: true
dist: xenial

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

# install qemu-user before running docker build
before_install:
  - |
   if ! git diff --name-only $TRAVIS_BRANCH...HEAD | grep -qvE '(.md)|^(LICENSE)'
   then
     echo "Not running CI since only docs were changed."
     exit
   fi

# Only clone the most recent commit.
git:
  depth: 1
